#!/bin/bash
# openCV
mkdir /tmp/openCV/
cd /tmp/openCV/
wget https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
git clone https://github.com/opencv/opencv.git
cd opencv
git checkout 3.0.0
cd ~/opencv
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE \
	-D CMAKE_INSTALL_PREFIX=/usr/local \
	-D INSTALL_C_EXAMPLES=ON \
	-D INSTALL_PYTHON_EXAMPLES=ON \
	-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
	-D BUILD_EXAMPLES=ON ..
make -j4
sudo make install
sudo ldconfig
sudo cp -r opencv/samples/data/ /usr/local/share/OpenCV/samples/