#!/bin/bash
# install arduino
wget -O /tmp/arduino-nightly.tar.xz https://www.arduino.cc/download.php?f=/arduino-nightly-linux64.tar.xz
cd /tmp/
tar -xf arduino-nightly.tar.xz 
cd arduino-nightly/
./install.sh
